---
apiVersion: v1
kind: Pod
metadata:
  name: word-rep
  namespace: 1team
  labels:
    run: myword
spec:
  containers:
  - name: word
    image: wordpress:5.6
    imagePullPolicy: IfNotPresent
    env:
    - name: WORDPRESS_DB_HOST
      value: word-rep
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: It12345!
    ports:
    - containerPort: 80
  - name: mysql
    image: mysql:5.7
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: It12345!
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_ROOT_HOST
      value: '%'
    ports:
    - containerPort: 3306
